os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build test -workspace Pokedex.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
